# Generated by Django 2.1 on 2018-08-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=80)),
                ('user_lname', models.CharField(max_length=80)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_isactive', models.BooleanField()),
                ('user_password', models.CharField(max_length=500)),
                ('user_verf_link', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
