# Generated by Django 2.1 on 2018-08-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_isactive',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_verf_link',
        ),
    ]
