# Generated by Django 2.1 on 2018-08-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='slot_date',
        ),
    ]
