# Generated by Django 2.1 on 2018-08-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20180806_0444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
