# Generated by Django 2.1 on 2018-08-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
