# Generated by Django 2.1 on 2018-08-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_bookings_is_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='slot_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='slot_time',
            field=models.DateTimeField(),
        ),
    ]
