# Generated by Django 2.1 on 2018-08-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20180806_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
