# Generated by Django 2.1 on 2018-08-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_bookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='slot_date_time',
            new_name='slot_date',
        ),
    ]
