# Generated by Django 2.1 on 2018-08-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_auto_20180806_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
