# Generated by Django 2.1 on 2018-08-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='is_scheduled',
            field=models.BooleanField(),
        ),
    ]
